version: "3.3"
services:
  web:
    image: nginx:stable
    container_name: webserver
    ports:
      - "8088:80"
      - "444:443"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    build: ./app
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./app/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini